#ifndef RETHINKING_SIMD_VECTORIZATION_FOR_IN_MEMORY_DATABASES_PARTITIONING_H
#define RETHINKING_SIMD_VECTORIZATION_FOR_IN_MEMORY_DATABASES_PARTITIONING_H

#include "TableSchema.h"

int runPartitioning(int tableSize, int cycle, int partitionNums);

#endif //RETHINKING_SIMD_VECTORIZATION_FOR_IN_MEMORY_DATABASES_PARTITIONING_H

