#ifndef RETHINKING_SIMD_VECTORIZATION_FOR_IN_MEMORY_DATABASES_SELECTIONSCAN_H
#define RETHINKING_SIMD_VECTORIZATION_FOR_IN_MEMORY_DATABASES_SELECTIONSCAN_H

#include "TableSchema.h"

int runSelectionScan(int min, int max, int tableSize);

#endif //RETHINKING_SIMD_VECTORIZATION_FOR_IN_MEMORY_DATABASES_SELECTIONSCAN_H

