/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniDemo */

#ifndef _Included_JniDemo
#define _Included_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniDemo
 * Method:    runExpressionEval
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniDemo_runExpressionEval
  (JNIEnv *, jobject);

/*
 * Class:     JniDemo
 * Method:    runLimitTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniDemo_runLimitTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
