env = Environment(CC = "gcc", CXX = "g++", CXXFLAGS = "-Wall -g -O0")

env.SConscript('thirdparty/sqlite3/SConscript')
env.SConscript('thirdparty/gtest/SConscript')
#env.SConscript('thirdparty/gmock/SConscript')
env.SConscript('thirdparty/cjson/SConscript')

libs = ['leveldb', 'snappy', 'pthread', 'mysqlite3', 'mysqlcppconn', 'tcmalloc', 'curl', 'cjson', 'libevent']
test_libs = libs + ['gtest', 'gtest_main', 'hello_cpp']

libs_path = ['thirdparty/cjson', 'thirdparty/sqlite3/lib/']
test_libs_path = libs_path + ['thirdparty/gtest/lib', '.']

for sf in Glob('src/*.cpp'):
    env.Program(target = sf.name.split('/')[-1][0:-4], 
                source = [sf], 
                CPPPATH = ['src', 'thirdparty/sqlite3', 'thirdparty/cjson'], 
                LIBS = libs, 
                LIBPATH = libs_path)

for sf in Glob('lib/*.cpp'):
    env.StaticLibrary(target = sf.name.split('/')[-1][0:-4], 
                source = [sf], 
                CPPPATH = ['lib'], 
                LIBS = libs, 
                LIBPATH = libs_path)

for sf in Glob('unittest/*.cpp'):
    env.Program(target = sf.name.split('/')[-1][0:-4] + '_unittest', 
                source = [sf], 
                CPPPATH = ['thirdparty/gtest/include', 'lib'], 
                LIBS = test_libs, 
                LIBPATH = test_libs_path)

# proto
env.Object('proto/addressbook.pb.cc')
env.Program(target = 'addressbook_writer', 
            source = Glob('proto/addressbook_writer.cpp') + Glob('proto/addressbook.pb.o'),
            CPPPATH = ['proto'],
            LIBS = ['protobuf'],
            LIBPATH = [])
env.Program(target = 'addressbook_reader', 
            source = Glob('proto/addressbook_reader.cpp') + Glob('proto/addressbook.pb.o'),
            CPPPATH = ['proto'],
            LIBS = ['protobuf'],
            LIBPATH = [])