#!/bin/bash

set -u
set -e

DEBUG="OFF"

export CURRENT_DIR=$(cd `dirname $0`; pwd)
export INSTALL_PREFIX=$(cd ${CURRENT_DIR}/deps; pwd)

# -DCMAKE_SKIP_RPATH=TRUE remove rpath
# -DCMAKE_PREFIX_PREFIX 设置 cmake find_package 的路径
# find_package will search ${PATH} firstly
export PATH=${INSTALL_PREFIX}:$PATH
#export EXTRA_CMAKE_FLAGS="-DCMAKE_MODULE_PATH=${INSTALL_PREFIX} -DCMAKE_PREFIX_PREFIX=${INSTALL_PREFIX} -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DBUILD_SHARED_LIBS=ON"
export EXTRA_CMAKE_FLAGS="-DCMAKE_MODULE_PATH=${INSTALL_PREFIX} -DCMAKE_PREFIX_PREFIX=${INSTALL_PREFIX} -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}"
if [[ ( "${DEBUG}" == "DEBUG" ) || ( "${DEBUG}" == "ON" ) ]]; then
    export EXTRA_CMAKE_FLAGS="${EXTRA_CMAKE_FLAGS} -DCMAKE_FIND_DEBUG_MODE=1"
else
    export EXTRA_CMAKE_FLAGS="${EXTRA_CMAKE_FLAGS} -DCMAKE_FIND_DEBUG_MODE=0"
fi

export SETUP_EXTRA_CMAKE_FLAGS=${EXTRA_CMAKE_FLAGS}
export MY_INSTALL_DIR=${INSTALL_PREFIX}

cd ${CURRENT_DIR}

cd ${CURRENT_DIR}/velox

bash -x ${CURRENT_DIR}/velox/scripts/setup-macos.sh
